chore: dont npm ignore custom resource handlers (#26379)
In this [PR](https://github.com/aws/aws-cdk/pull/26287), we moved the custom resource handlers from the `lib` directory to `dist` - but any `dist` directory is npm ignored.

This is causing failures in our pipeline when running cli integration tests:

```console
Error: cannot find /tmp/cdk-integ-0u3tmsd7dnl/node_modules/aws-cdk-lib/custom-resource-handlers/dist/aws-s3/auto-delete-objects-handler/index.js
--
242 | at new CustomResourceProvider (/tmp/cdk-integ-0u3tmsd7dnl/node_modules/aws-cdk-lib/core/lib/custom-resource-provider/custom-resource-provider.js:1:3214)
243 | at Function.getOrCreateProvider (/tmp/cdk-integ-0u3tmsd7dnl/node_modules/aws-cdk-lib/core/lib/custom-resource-provider/custom-resource-provider.js:1:2660)
244 | at Bucket.enableAutoDeleteObjects (/tmp/cdk-integ-0u3tmsd7dnl/node_modules/aws-cdk-lib/aws-s3/lib/bucket.js:1:32627)
245 | at new Bucket (/tmp/cdk-integ-0u3tmsd7dnl/node_modules/aws-cdk-lib/aws-s3/lib/bucket.js:1:21317)
246 | at new BuiltinLambdaStack (/tmp/cdk-integ-0u3tmsd7dnl/app.js:379:5)
247 | at Object.<anonymous> (/tmp/cdk-integ-0u3tmsd7dnl/app.js:449:5)
248 | at Module._compile (node:internal/modules/cjs/loader:1196:14)
249 | at Object.Module._extensions..js (node:internal/modules/cjs/loader:1250:10)
250 | at Module.load (node:internal/modules/cjs/loader:1074:32)
```

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*